#!/bin/bash

## #ddev-generated
## Description: Install magento and mageforge module
## Usage: install-magento
## Example: ddev install-magento

# global config
MAGENTO_FOLDER="magento"
MODULE_FOLDER="src/"

# check if magento directory is empty
if [ -n "$(ls ${MODULE_FOLDER})" ]; then
    echo "${MODULE_FOLDER} directory is not empty. Skipping execution of install-magento."
    exit 0
fi

# download magento
composer create-project \
    --repository-url=https://mirror.mage-os.org/ \
    magento/project-community-edition \
    magento-temp

# copy everything from magento-temp into magento folder
cp -r magento-temp/* ${MAGENTO_FOLDER}

# remove magento-temp
rm -rf magento-temp

# change to magento directory
cd ${MAGENTO_FOLDER} || exit 1

# install magento
bin/magento setup:install \
    --admin-email=admin@mageforge.ddev.site \
    --admin-firstname=Mage \
    --admin-lastname=Forge \
    --admin-password=admin123 \
    --admin-user=admin \
    --backend-frontname=admin \
    --db-host=db \
    --db-name=db \
    --db-password=db \
    --db-user=db \
    --search-engine=opensearch \
    --opensearch-host=opensearch \
    --opensearch-port=9200 \
    --base-url=https://mageforge.ddev.site/ \
    --language=en_US

# install sample data
bin/magento sampledata:deploy

# add repository
composer config repositories.mageforge vcs https://github.com/dermatz/mageforge.git

# require module
composer require mageforge/base:dev-main --prefer-source

# enable module
bin/magento setup:upgrade
